phst/rules_elisp

elisp/file_test.cc

* using decl 'Ge' is unused
* using decl 'Not' is unused

Fix 2 ClangTidyReadability findings:

---

.github/workflows/bazel-test.yaml

Pass the provided token to Bazelisk so that we don’t run into rate limits.  See
https://github.com/bazelbuild/bazelisk/issues/88#issuecomment-625178467.

Try to reduce flakiness on GitHub runners.

---

.githooks/pre-commit
.github/workflows/bazel-test.yaml
build.py

It doesn’t make sense to generate files in the pre-commit hook or in the
continuous integration pipeline.

Split up build script into ‘check’ and ‘generate’ targets.

---

.github/workflows/bazel-test.yaml
build.py

The repository cache should only depend on the contents of WORKSPACE and
Starlark files, but not on the OS and Bazel version,
cf. https://docs.bazel.build/versions/4.2.2/guide.html#the-repository-cache.
Right now the cache is so big that it’s always evicted.  Keying the repository
cache on WORKSPACE and Starlark file contents only should reduce the overall
cache size.

Use separate cache keys for repository cache.

---

build.py

This reverts commit acae5642ac37d9e525320f6282a3d848c0f8c1a9.
I haven't seen much flakiness recently; especially the disk cache and avoiding Xcode
appears to have improved things substantially.

Revert "Retry failed Bazel runs on GitHub."

---

WORKSPACE

See https://github.com/bazelbuild/rules_python/releases/tag/0.6.0.

Update rules_python dependency.

---

docs/emacs.md
elisp/repositories.bzl
emacs/BUILD
emacs/build.py
emacs/defs.bzl
gazelle/BUILD
gazelle/builtin.go
gazelle/feature.go
gazelle/gazelle_test.go
gazelle/generate.go
gazelle/generate_test.go
gazelle/imports.go
gazelle/imports_test.go
gazelle/language.go
gazelle/loadpath.go
gazelle/resolve.go
gazelle/resolve_test.go
gazelle/source.go

See https://github.com/bazelbuild/bazel-gazelle/blob/master/extend.md.

Add basic Gazelle support for Emacs Lisp.

---

.github/workflows/bazel-test.yaml

See https://github.com/bazelbuild/bazel/releases/tag/5.0.0.

Run tests under newly-released Bazel 5.

---

.github/workflows/bazel-test.yaml
WORKSPACE

See https://github.com/bazelbuild/rules_go/releases/tag/v0.30.0.

Update to newest rules_go release.

---

.github/workflows/bazel-test.yaml

It seems that they are now missing from the default runner installation.

Install missing MSYS2 packages.

---

check_python.py

Otherwise removing the copies might fail later if they come from an external
workspace.

Don’t copy file permissions into temporary workspace.

---

docs/merge.el

‘org-export’ strips too much away from the included files, but we want to keep
e.g. Texinfo-specific keywords intact.

Only expand includes and don’t go through full export cycle.

---

elisp/process.cc

This was broken by commit ba30451c45f140ee0c864a8e13a093a852ac3960.

Fix build on Windows.

---

elisp/util.bzl

This should improve reproducibility.

Pass --no-build-details to Emacs wherever possible.

---

.github/workflows/bazel-test.yaml

This is necessary because on the GitHub runner Visual C++ 2022 is also
installed, but doesn’t work with Bazel.

Explicitly specify Visual C++ location.

---

WORKSPACE

See https://github.com/bazelbuild/rules_python/releases/tag/0.7.0.

Update to new rules_python release.

---

elisp/repositories.bzl

See https://github.com/bazelbuild/bazel-skylib/releases/tag/1.2.1.

Update to Skylib 1.2.1.

---

constraints/BUILD
elisp/BUILD

We now only use Visual C++ in the CI system, so these combinations are untested.

Remove support for MinGW and Clang on Windows.

---

build.py
elisp/BUILD
elisp/ert/runner.el
elisp/repositories.bzl
elisp/runfiles/runfiles-test.el
elisp/runfiles/runfiles.el
emacs/BUILD

See https://lists.gnu.org/archive/html/emacs-devel/2022-04/msg00093.html.

Add support for newly-released Emacs 28.1.

---

elisp/proto/proto-test.el

All supported Emacs versions now support the modern calling convention.

Avoid obsolescent calling convention for ‘encode-time’.

---

elisp/runfiles/runfiles-test.el
elisp/runfiles/runfiles.el

This is equivalent to the fixes made for
https://github.com/bazelbuild/bazel/issues/14336.

Support manifest runfiles that map to directories.

---

elisp/runfiles/runfiles-test.el

This decouples the test from EIEIO.

Use ‘cl-typep’ instead of ‘object-of-class-p’.

---

elisp/proto/generate.el
elisp/proto/proto.el
elisp/runfiles/runfiles.el

Edebug doesn’t detect the list form before commit
f3df7916b2b342380930082cf35bad6cb488a4dc, and that commit is not present in any
released version of Emacs.

Use keyword-only form for :noinline structure option.

---

elisp/repositories.bzl

See https://github.com/protocolbuffers/protobuf/releases/tag/v3.20.1.

Update protocol buffer dependency.

---

WORKSPACE

See https://github.com/bazelbuild/rules_python/releases/tag/0.8.1.

Update to newest rules_python release.

---

WORKSPACE
private/defs.bzl

These are now natively supported by rules_python,
cf. https://github.com/bazelbuild/rules_python/pull/531.  This means we can now
remove our hand-rolled support for per-platform requirements.

Use per-platform pip requirements.

---

.github/workflows/bazel-test.yaml
WORKSPACE
docs/manual.org

The µpb dependency now requires at least Bazel 5.1.

Drop support for Bazel 4 and 5.0.

---

elisp/defs.bzl

Part of https://github.com/bazelbuild/bazel/issues/14727

Use a helper to to define the cpp toolchain type

---

.github/workflows/bazel-test.yaml

This test currently fails due to
https://github.com/bazelbuild/bazel/issues/15919.

Temporarily exclude failing test matrix element.

---

elisp/repositories.bzl

See https://github.com/protocolbuffers/protobuf/releases/tag/v21.4.

Update to Protocol Buffers 21.4.

---

linux-requirements.txt
macos-requirements.txt
requirements.in
windows-requirements.txt

See https://github.com/PyCQA/pylint/releases/tag/v2.15.0.

Update to Pylint 2.15.

---

linux-requirements.txt
macos-requirements.txt
requirements.in
windows-requirements.txt

See https://github.com/PyCQA/pylint/releases/tag/v2.15.2.

Update to Pylint v2.15.2.

---

bazel/BUILD
bazel/protobuf.patch
elisp/repositories.bzl

This unblocks updating µpb, because newer versions depend on unreleased incompatible versions of Protocol Buffers.

Use protocol buffer dependency through µpb.

---

elisp/repositories.bzl

See https://github.com/protocolbuffers/protobuf/releases/tag/v21.9.

Update to newest protocol buffer release.

---

elisp/repositories.bzl
emacs-27.patch

Without this, Emacs 27 no longer compiles under newer Debian/Ubuntu versions because SIGSTKSZ is no longer a constant.

Backport patch for Emacs 27.

---

elisp/repositories.bzl

See https://github.com/protocolbuffers/protobuf/releases/tag/v21.11.

Update to Protocol Buffers v21.11.

---

.github/workflows/bazel-test.yaml

See https://github.com/bazelbuild/bazel/releases/tag/6.0.0.

Run tests under newly-released Bazel 6.0.0.

---

check_python.py

Otherwise it tries to infer the path from the source files (ignoring the PYTHONPATH environment variable), which typically fails in our setup.

Specify Python import path explicitly for Pytype.

---

check_python.py
docs/generate.py
elisp/load.py
elisp/load_test.py
elisp/manifest_test.py
elisp/run_binary.py
elisp/run_emacs.py
elisp/run_test.py
elisp/runfiles.py
emacs/emacs_test.py
examples/bin_test.py
tests/wrap/wrap.py

With Bzlmod, workspace names under the runfiles root won’t be stable any more and therefore shouldn’t be used as part of module names.

Don’t include the runfiles root in the Python imports path.

---

elisp/repositories.bzl

See https://github.com/bazelbuild/platforms/releases/tag/0.0.6.

Explicitly depend on platform repository.

---

docs/manual.org
elisp/proto/module.c
elisp/proto/proto-test.el

This isn't supported in the release branch yet.
This reverts commit a7454084f8f2d591bc598ddef9fbc387e5e803ee.

Revert "Add support for outputting enumerator values in JSON"

---

build.py

This doesn’t seem to be necessary.

Remove postfix options from build script.

---

WORKSPACE

See https://github.com/bazelbuild/rules_python/releases/tag/0.16.1.

Update to rules_python 0.16.1.

---

WORKSPACE

See https://github.com/bazelbuild/rules_go/releases/tag/v0.37.0.

Update to rules_go v0.37.0.

---

elisp/repositories.bzl
elisp/unix-toolchains.BUILD
elisp/windows-toolchains.BUILD
emacs/BUILD
emacs/emacs_test.py

This simplifies the repository rules quite a bit.

Move Emacs BUILD rules into main workspace.

---

elisp/BUILD
elisp/binary_test.cc
emacs/BUILD
emacs/emacs_test.py
tests/BUILD
tests/ert_test.go

This saves us the hassle of appending the .exe suffix manually.

Use “rootpath” for finding binaries.

---

WORKSPACE

Turns out that this is necessary after all.
This reverts commit 9c959eb57ff565e03d371c98dfdd47b8bcb3a8d4.

Revert "Don’t register hermetic Python toolchains."

---

BUILD
constraints/BUILD
elisp/proto/BUILD
emacs/BUILD
examples/BUILD
private/defs.bzl

All supported versions of Bazel now support selecting on constraint_value rules directly.

Remove unnecessary config_setting rules.

---

emacs/BUILD

This reverts commit 30d161709a063656ddf3c0acfca67a8b4c5d2d37.
By now we only support Bazel versions that have @platforms//:incompatible.

Revert "Don’t use @platforms//:incompatible; it’s not released yet."

---

WORKSPACE

See https://github.com/google/googletest/releases/tag/release-1.12.1.

Update to GoogleTest 1.12.1.

---

WORKSPACE

See https://github.com/bazelbuild/rules_python/releases/tag/0.18.1.

Update to rules_python 0.18.1.

---

elisp/repositories.bzl

See https://github.com/protocolbuffers/protobuf/releases/tag/v21.7.

Update to Protocol Buffers v21.7.

---

.github/workflows/bazel-test.yaml

Otherwise there are just too many elements in the test matrix.

Don’t test each point release of Bazel individually.

---

elisp/ert/runner.el
elisp/proto/generate.el

With commit 5ee4209f307fdf8cde9775539c9596d29edccd6d, Emacs no longer treats ‘proper-list’ and ‘buffer-live’ as types, so use equivalent predicates instead.

Improve compatibility with Emacs 29.

---

WORKSPACE

See https://github.com/bazelbuild/rules_python/releases/tag/0.20.0.

Update to rules_python 0.20.0.

---

WORKSPACE

See https://github.com/bazelbuild/rules_go/releases/tag/v0.39.0.

Update to rules_go v0.39.0.

---

elisp/repositories.bzl

See https://github.com/bazelbuild/platforms/releases/tag/0.0.6.

Update to platforms 0.0.6.

---

elisp/repositories.bzl

See https://github.com/bazelbuild/bazel-skylib/releases/tag/1.4.1.

Update to Skylib 1.4.1.

---

elisp/BUILD
elisp/binary_test.cc
emacs/BUILD
emacs/emacs_test.py
tests/BUILD
tests/ert_test.go

This saves us the hassle of appending the .exe suffix manually.

Use “rlocationpath” for finding binaries.

---

WORKSPACE

See https://github.com/bazelbuild/rules_python/releases/tag/0.22.0.

Update to rules_python 0.22.0.

---

elisp/runfiles/runfiles-test.el
elisp/runfiles/runfiles.el

This isn’t used in Emacs 28, but will be in Emacs 29.

Add runfile name handler for abbreviate-file-name.

---

.github/workflows/bazel-test.yaml

See https://github.com/bazelbuild/bazel/releases/tag/6.2.1.

Switch to newest point release of the Bazel 6.2 series.

---

.github/workflows/bazel-test.yaml

See https://github.com/bazelbuild/bazel/releases/tag/6.3.1.

Run tests under Bazel 6.3.1.

---

elisp/repositories.bzl

See https://github.com/bazelbuild/rules_python/releases/tag/0.24.0.

Update to rules_python 0.24.0.

---

elisp/proto/generate.el
private/defs.bzl

With Bzlmod, Bazel generates workspace names that contain tilde characters, so we need to allow them if we want to support Bzlmod.

Allow tilde character in filenames.

---

elisp/BUILD
elisp/runfiles.py

The one built into Bazel doesn’t support repository mappings (and therefore doesn’t support modules).

Use runfiles library from rules_python.

---

WORKSPACE
docs/BUILD
elisp/BUILD
elisp/repositories.bzl
private/BUILD
private/repositories.bzl

That will allow us to reuse the newly-added function when enabling Bzlmod.

Factor out dependencies that are not available as modules.

---

elisp/run_test.py

Now that it might be unset in the original environment, read it from the modified one instead (after modification).

Fix logic around COVERAGE_DIR.

---

elisp/run_binary.py
elisp/run_test.py

The difference between the original and the modified environment shouldn’t matter in practice.

Remove orig_env variables.

---

.github/workflows/bazel-test.yaml

This reverts commit eb4ebfecc31c205ff8a1525e3849f7b60477ab52.

Revert "Temporarily skip rolling release tests."

---

MODULE.bazel

The “dev_dependency” setting must match the one from the “bazel_gazelle” repository.

Mark Go extensions as development-only dependency.

---

elisp/defs.bzl
emacs/defs.bzl
private/defs.bzl

`grep_includes` are not needed anymore in cc_link.

Remove grep_includes

---

emacs/build.py

This reverts commit 04ade730f0d32a35b2e4d56c5ee8d4739bedf478.
The sanity check doesn't seem to work right on Windows (doesn't find the portable dump file) and shouldn't be needed.

Revert "Add a sanity check that the built Emacs binary works"

---

elisp/BUILD
tests/BUILD
tests/empty.el
tests/empty_test.py

Realistically it only produces output if e.g. Emacs can’t find the portable dump file.

Add a test that the empty binary doesn’t produce output.

---

.github/workflows/bazel-test.yaml

See https://github.com/bazelbuild/bazel/releases/tag/6.4.0.

Run tests under Bazel 6.4.

---

MODULE.bazel
elisp/repositories.bzl

See https://github.com/bazelbuild/rules_python/releases/tag/0.26.0.

Update rules_python to version 0.26.0.

---

MODULE.bazel
WORKSPACE

See https://github.com/bazelbuild/rules_go/releases/tag/v0.42.0.

Update to rules_go 0.42.0.

---

MODULE.bazel
examples/ext/MODULE.bazel

This will make the local registry unnecessary.

Use local_path_override for in-tree repositories.

---

MODULE.bazel
elisp/repositories.bzl

See https://github.com/bazelbuild/bazel-skylib/releases/tag/1.5.0.

Update to Skylib 1.5.0.

---

.bazelrc

This reverts commit 32ffda14d952b1809f6882a76bb7a46c923a9e21.
Maybe we don’t need this any more.

Revert "Improve heap size on Visual C++."

---

WORKSPACE
docs/BUILD
elisp/BUILD
elisp/extensions.bzl
elisp/repositories.bzl
examples/ext/BUILD
examples/ext/MODULE.bazel
examples/ext/WORKSPACE
examples/ext/lib-4.el
examples/ext/repositories.bzl
private/repositories.bzl

Add a repository rule and an equivalent module extension that behaves like http_archive, but makes the archive contents available as an elisp_library.

Add basic support for external Emacs Lisp dependencies.

---

.github/workflows/bazel-test.yaml
c-std.bazelrc

--per_file_copt doesn’t work right with our generated launcher files.

Attempt to use --cxxopt on Windows again.

---

elisp/compile.el
elisp/defs.bzl
elisp/runfiles/runfiles.el
private/defs.bzl

This should making the runfiles machinery to detect the source repository a bit more robust.

Inject current repository name when compiling.

---

.github/workflows/bazel-test.yaml

See https://github.com/bazelbuild/bazel/releases/tag/7.0.0.

Run tests under newly-released Bazel 7.

---

MODULE.bazel
MODULE.bazel.lock
docs/BUILD
docs/generate.py
docs/manual.org
docs/merge.el
examples/ext/MODULE.bazel.lock
private/defs.bzl
private/repositories.bzl

This requires workarounds for https://github.com/bazelbuild/stardoc/issues/192 and https://github.com/bazelbuild/bazel/issues/8305.

Document module extensions if possible.

---

MODULE.bazel
MODULE.bazel.lock
WORKSPACE
examples/ext/MODULE.bazel.lock

See https://github.com/bazelbuild/rules_go/releases/tag/v0.44.0 and https://github.com/bazelbuild/bazel-gazelle/releases/tag/v0.35.0.

Update to rules_go 0.44.0 and Gazelle 0.35.0.

---

MODULE.bazel
MODULE.bazel.lock
elisp/defs.bzl
elisp/proto/module.c
elisp/repositories.bzl
examples/ext/MODULE.bazel.lock
protobuf.patch
upb.patch

Update Protocol Buffers dependency to 23.1.
See https://github.com/protocolbuffers/protobuf/releases/tag/v23.1.
Update μpb to version 0.0.0-20230516-61a97ef.

Update Protocol Buffers and μpb dependencies.

---

emacs/BUILD

This workaround should no longer be needed.
Effectively revert commit d3acb2afb69c631c39692e5da2e895b2656fe82d.

Remove a workaround for https://bugs.gnu.org/48303.

---

emacs/BUILD

This reverts commit 9b7747d424f5b782aaa4ba73a92d1f753cc2aee2.
After dropping support for Emacs 27, all supported Emacs versions should support the same set of platforms.  Attempting to restrict platforms adds unnecessary complexity.

Revert "Restrict Emacs binaries to platforms that they actually support."

---

build.py

Bazel already does that if the filename starts with “~/”, see https://bazel.build/remote/caching#disk-cache and the code in com.google.devtools.build.lib.util.OptionsUtils.convertOptionsPathFragment. Because only a literal “~/” prefix is detected, use PurePosixPath instead of Path.

Don’t expand cache directories in build.py.

---

.github/workflows/bazel-test.yaml
build.py

It’s easier that way, and also works interactively.

Use build.py for --lockfile_mode and --enable_bzlmod flags.

---

elisp/binary.cc
elisp/binary_test.cc
elisp/emacs.cc
elisp/process.cc
elisp/test.cc

This should be the case in all Bazel versions starting with 6.0, cf. https://www.buildbuddy.io/blog/whats-new-in-bazel-6-0/#c-and-c.

Assume that BAZEL_CURRENT_REPOSITORY is always defined.

---

build.py
update_readme

With Bazel 6, Bzlmod is no longer experimental.  See https://github.com/bazelbuild/bazel/releases/tag/6.0.0.

Use --enable_bzlmod instead of --experimental_enable_bzlmod.

---

elisp/BUILD
elisp/binary.cc
elisp/emacs.cc
elisp/process.cc
elisp/test.cc
private/defs.bzl

This removes a dependency on the workspace name.

Use local defines for runner binaries.

---

elisp/BUILD
elisp/binary_main.cc
elisp/defs.bzl
elisp/test_main.cc
emacs/BUILD
emacs/defs.bzl
emacs/launcher.cc
private/defs.bzl

This means that the launcher templates become syntactically valid C++ files.

Use preprocessor definitions for launchers instead of templates.

---

private/defs.bzl

This is recommended in https://bazel.build/rules/lib/builtins/runfiles#merge.

Use runfiles.merge_all instead of looping.

---

.github/actions/set-up/action.yaml
.github/workflows/bazel-test.yaml
.github/workflows/debug-cache.yaml
.github/workflows/update-lockfiles.yaml

Since Bazel 6.3, Visual C++ 2022 should be supported.  See https://github.com/bazelbuild/bazel/issues/18592 and https://github.com/bazelbuild/bazel/pull/18960.

Switch back to default Visual C++.

---

.github/workflows/bazel-test.yaml

See https://github.com/bazelbuild/bazel/releases/tag/6.5.0 and https://releases.bazel.build/6.5.0/release/index.html.

Run tests under newly-released Bazel 6.5.0.

---

elisp/defs.bzl

Starlark documents rules in definition order, and few users will want to define their own toolchain, so document it at the very end.

Move elisp_toolchain rule to the bottom of elisp/defs.bzl.

---

elisp/BUILD
elisp/binary.cc
elisp/binary_test.py
elisp/load.py
elisp/load_test.py
elisp/run_binary.py
elisp/run_test.py
elisp/test.cc
tests/BUILD
tests/ert_test.go

This again removes a few instances of the hard-coded workspace name.

Pass a few data dependencies in flags.

---

elisp/load_test.py

This test is supposed to test whether load path generation works given some hermetic setup, and it shouldn’t depend on the main workspace name.

Don’t use actual main repository name in load_test.py.

---

REPO.bazel
examples/ext/BUILD
examples/ext/REPO.bazel
private/defs.bzl

On Unix they aren’t used anyway, and on Windows they don’t work due to https://github.com/bazelbuild/bazel/issues/21029.

Disable compiler parameter files globally.

---

.github/workflows/bazel-test.yaml
build.py

No need to pollute the build script with this.
We only need to do this for bazel-test.yaml because all other workflows run only on Bazel 7, which only ships the Unix toolchain to begin with and ignores the variable.

Specify BAZEL_USE_CPP_ONLY_TOOLCHAIN in the GitHub workflow.

---

.bazelrc
examples/ext/.bazelrc

The idea is that the setup action can then put GitHub-specific flags into that file.

Read another .bazelrc file github.bazelrc if it exists.

---

.github/actions/set-up/action.yaml

This means that MSYS2 should always be installed in C:\MSYS64, so Bazel should discover it automatically.

Use default MSYS2 installation.

---

.github/workflows/bazel-test.yaml
.github/workflows/debug-cache.yaml
.github/workflows/update-lockfiles.yaml
build.py

We only ever use “bazelisk” or “bazel”.

Remove --bazel option for the build script.

---

.dir-locals.el
Makefile
build.py

We only develop on Unix platforms, and the Makefile is shorter and simpler. Continue using the Python script for CI, as that needs to be cross-platform.

Switch back to Makefile for local development.

---

.github/workflows/bazel-test.yaml
.github/workflows/debug-cache.yaml
.github/workflows/update-lockfiles.yaml

This should work on all
platforms (cf. https://bazel.build/configure/windows#running-bazel-shells), and means we don’t have to write “polyglot” commands.  See https://bazel.build/configure/windows#running-bazel-shells why we don’t use Bash.

Run Bazel under PowerShell on all platforms.

---

.github/workflows/update-lockfiles.yaml

We need to filter out module extension keys for the “wrong” OS because they will be stale.

Fix lockfile merging.

---

MODULE.bazel
MODULE.bazel.lock
WORKSPACE
examples/ext/MODULE.bazel.lock

See https://github.com/bazelbuild/rules_go/releases/tag/v0.46.0.

Update to rules_go 0.46.0.

---

elisp/process.cc

This reverts commit 3585d81f5c561ad7cbc150896c0d48e6298ce6d5.
The fix (https://github.com/bazelbuild/rules_python/pull/1734, https://github.com/bazelbuild/rules_python/commit/ebbcb6a548fbc1f62ec27a5aef6c815924ffbc66) is included in rules_python now.

Revert "Work around a potential Bazel bug related to Python coverage"

---

tests/ert_test.go

This reverts commit cddf5015e8abe5f478639dbe994655f54b7e3424.
This might no longer be needed.

Revert "Don’t allow the Python launcher to change the current directory"

---

elisp/BUILD
elisp/process.cc
elisp/process.h

We always sort the environment pairs anyway.

Use std::map for environment.

---

elisp/defs.bzl
emacs/defs.bzl
private/defs.bzl

Using ctx.actions.run(executable = ...) is sufficient to ensure that the runfiles are present.
Originally by @tjgq.

Remove unnecessary ctx.resolve_tools(...).

---

elisp/binary.cc
elisp/binary.h
elisp/binary_main.cc
elisp/emacs.cc
elisp/emacs.h
elisp/test.cc
elisp/test.h
elisp/test_main.cc
emacs/launcher.cc

Build up argument lists in the helper libraries instead of the main function.

Simplify launcher code.

---

elisp/BUILD
elisp/process.cc
elisp/process.h

This reverts commit f2918a27600d2e0514d69bf05b61de44adc67537.
Let's try to use LCMapString to generate the hash value.

Revert "Use std::map for environment."

---

elisp/binary_test.py

This reverts commit 7adb6dcee25fecb0b779e5305efc3cd0bb4905f1.
Issue https://github.com/bazelbuild/rules_python/issues/1394 is now fixed in rules_python.

Revert "Work around https://github.com/bazelbuild/rules_python/issues/1394"

---

elisp/BUILD
elisp/binary.cc
elisp/binary.h
elisp/defs.bzl
elisp/emacs.cc
elisp/emacs.h
elisp/test.cc
elisp/test.h
emacs/defs.bzl

We have exactly one of those in each launcher program.

Rename all the main functions to just “Main”.

---

private/defs.bzl

The "to_json" method on Starlark structs is deprecated and should not be used. Instead, the json module (https://bazel.build/rules/lib/core/json) should be used.

Replace instances of struct.to_json with json.encode(...)

---

elisp/process.cc

This reverts commit b6f8a415468f6521b2ec7306c8837c0105818741.
I guess it's not correct to ignore these variables after all; we should forward them to the child process.

Revert "Ignore all hidden environment variables on Windows"

---

elisp/run_emacs.py

The current ANSI codepage could differ between Emacs and the calling process.

Only support ASCII strings when invoking Emacs.

---

elisp/defs.bzl

Direct access is going away; this commit updates the code for that.

Indirect fields of ctx.attr.<name> through DefaultInfo.

---

.github/workflows/bazel-test.yaml
WORKSPACE
build.py
docs/manual.org

Protocol Buffers 26 will require at least Bazel 6.3.

Drop support for Bazel versions older than 6.3.

---

elisp/defs.bzl

We should take into account the source file root and its workspace root so that generated source files are handled correctly.

Improve computation of source load path.

---

elisp/defs.bzl
elisp/proto/BUILD
elisp/proto/generate-bundle.el
elisp/proto/generate.el

This mimics the behavior of other languages like Python and Go.
To stay compatible, continue generating an overall Emacs Lisp file that loads the newly-generated files.

Generate one Emacs Lisp file per .proto file.

---

MODULE.bazel
MODULE.bazel.lock
elisp/repositories.bzl
emacs/BUILD
examples/ext/MODULE.bazel.lock
private/extensions.bzl
private/repositories.bzl

This reverts commit d5ce41500139ec52dfc73e079f63021dc60cfc96.
At least for the Emacs repositories it's better to use one repository per Emacs source archive, to prevent needless downloads.

Revert "Use only two repositories for non-module dependencies"

---

elisp/defs.bzl
elisp/proto/generate.el

Now that we have one .proto.el file per .proto file, mentioning the target isn’t very helpful.

Remove Bazel target label from generated proto file.

---

.github/actions/set-up/action.yaml

This reverts commit 90456291001a8fd952c4bfba6fa1e411f33a5838.
This should no longer be needed with newer Protobuf versions.

Revert "Install missing ‘realpath’ binary on macOS."

---

MODULE.bazel.lock
emacs.BUILD
emacs/build.py
emacs/defs.bzl
examples/ext/MODULE.bazel.lock
private/repositories.bzl

This allows us to drop the README hack.

Support Emacs source archives in emacs_binary.

---

emacs/defs.bzl

Apparently on some macOS/Clang versions the combination -undefined dynamic_lookup
followed by
-undefined error
doesn’t work correctly.

Add -undefined dynamic_lookup filtering into Starlark code.

---

MODULE.bazel
MODULE.bazel.lock
elisp/repositories.bzl
examples/ext/MODULE.bazel.lock

See https://github.com/bazelbuild/bazel-skylib/releases/tag/1.6.0.

Update to Skylib 1.6.0.

---

elisp/binary_test.py

Current code fails with strict dependencies:
```
ERROR: Strict deps violations: //third_party/elisp/rules/elisp:binary_test
In third_party/elisp/rules/elisp/binary_test.py, no direct deps found for imports:
line 22: from absl.flags import FLAGS: Ambiguous import: "FLAGS" from package "absl.flags": cannot determine whether "FLAGS" is an attribute on the package, or a module not provided by a direct dependency. See go/py-strict-deps#package-imports
```

Fix dependency issue with absl.flags.FLAGS.

---

MODULE.bazel
MODULE.bazel.lock
WORKSPACE
examples/ext/MODULE.bazel.lock

See https://github.com/bazelbuild/bazel-gazelle/releases/tag/v0.36.0.

Update to Gazelle 0.36.0.

---

docs/BUILD
private/defs.bzl

Newer versions of Stardoc require Bazel 7,
cf. https://github.com/bazelbuild/stardoc/releases/tag/0.7.0.

Don’t build Stardoc targets by default under Bazel 6.

---

docs/BUILD
docs/manual.org
docs/merge.el
private/defs.bzl

This partially reverts commit 8186377e787a0be4a8d9cdc14ccf7cd3628453d4.

Remove unused functionality to exclude tags from the manual.

---

elisp/export-org.el

This protects them against possible changes to ‘default-directory’.

Expand filenames eagerly.

---

elisp/export-org.el

Set ‘default-directory’ to the directory of the visited file so that relative filenames are interpreted correctly.

Mimic some aspects of file visiting.

---

elisp/runfiles/runfiles-test.el

Bazel supports them with https://github.com/bazelbuild/bazel/pull/23331.
Step 1: support them for directory-based runfiles.  This doesn’t require any code changes, just adapt the test.

Support space and backslash characters in runfile filenames.

---

MODULE.bazel
MODULE.bazel.lock
WORKSPACE

See https://github.com/bazelbuild/rules_go/releases/tag/v0.50.1.

Update to rules_go v0.50.1.

---

elisp/proto/BUILD

Now a library of kind ‘upb_FOO_library’ is consistently named ‘…_upb_FOO’.

Harmonize μpb library target names.

---

elisp/BUILD
emacs/BUILD
private/defs.bzl

Neither rules_cc nor bazel_tools from any supported Bazel version pass -undefined dynamic_lookup any more.

Remove -undefined dynamic_lookup workaround.

---

WORKSPACE

It’s a
no-op (cf. https://github.com/bazelbuild/rules_license/blob/1.0.0/deps.bzl), and the
documentation (https://github.com/bazelbuild/rules_license/releases/tag/1.0.0) doesn’t recommend its use any more.

Remove rules_license_dependencies.

---

WORKSPACE

This symbol was removed in
https://github.com/bazelbuild/rules_python/commit/68d1b4104f1d6f72ed0f3a8a5bf0a75d94cb74ec. See
https://rules-python.readthedocs.io/en/latest/getting-started.html#using-a-workspace-file for the documented alternative.

Don’t load ‘interpreter’ symbol from Python toolchain.

---

examples/ext/WORKSPACE

rules_elisp_dependencies already brings in an up-to-date version of rules_python.

Remove unnecessary http_archive stanza.

---

MODULE.bazel
WORKSPACE
docs/manual.org
examples/ext/WORKSPACE

This means that we benefit from toolchain improvements in rules_cc, independent of the Bazel version.

Register local C/C++ toolchain from rules_cc.

---

REPO.bazel
examples/ext/REPO.bazel
private/BUILD
private/defs.bzl

We now use the toolchain configuration from rules_cc, which has the fix to https://github.com/bazelbuild/bazel/issues/20919, independent of the Bazel version.

Enable treat_warnings_as_errors feature unconditionally.

---

REPO.bazel
examples/ext/REPO.bazel
private/defs.bzl

This should reduce the noise necessary to disable warnings.

Treat external repositories as system headers for warning purposes.

---

emacs/BUILD

cc_toolchain_suite is a no-op in Bazel 8.

Remove cc_toolchain_suite rule.

---

.bazelrc
elisp/binary.cc
elisp/binary.h
elisp/emacs.cc
elisp/emacs.h
elisp/launcher.cc
elisp/process.cc
elisp/process.h
elisp/proto/module.c
elisp/test.cc
private/defs.bzl

Otherwise newer versions of Abseil fail to compile.

Visual C++: lower external warning level to 2.

---

elisp/BUILD
elisp/ert/BUILD
elisp/proto/BUILD
emacs/BUILD

These were needed for Bazel 7.0.

Remove some visibility workarounds.

---

.dir-locals.el
MODULE.bazel
build.py
dev/BUILD
dev/gopackagesdriver
docs/BUILD
elisp/BUILD
elisp/defs.bzl
elisp/proto/BUILD
emacs/BUILD
examples/BUILD
gazelle/BUILD
private/defs.bzl
tests/BUILD

The renaming was only necessary for compatibility with WORKSPACE-only builds.

Don’t rename repositories in MODULE.bazel.

---

.github/actions/set-up/action.yaml

The setup-bazel action sets the output base on Windows to D:\_bazel, which should be short enough to avoid
https://github.com/protocolbuffers/protobuf/issues/12947.

Don’t override the output base.

---

.github/actions/set-up/action.yaml

The contents of github.bazelrc don’t contain backslashes any more.

Remove unnecessary use of ‘tr’.

---

.github/actions/set-up/action.yaml
.github/workflows/bazel-test.yaml

Workflows that want a different lockfile mode already override it on the command line.

Set lockfile mode in setup action.

---

.bazelrc
examples/ext/.bazelrc

This reverts commit d03524ae8566e22c1043fe82deda1c3a8bd725eb.
We don't write anything to github.bazelrc any longer.

Revert "Read another .bazelrc file github.bazelrc if it exists."

---

.github/actions/set-up/action.yaml
.github/workflows/bazel-test.yaml
.github/workflows/debug-cache.yaml
.github/workflows/update-lockfiles.yaml

The setup-bazel action now sets this variable,
cf. https://github.com/bazel-contrib/setup-bazel/issues/57.

Remove BAZELISK_GITHUB_TOKEN environment variable.

---

MODULE.bazel

This reverts commit 73f900b00b1b1c72d58d5ec49db2d17bba6225b0.
Renovate can only update git_override, not archive_override, cf. https://docs.renovatebot.com/bazel/#archive_override-and-local_path_override.

Revert "Use archive_override instead of git_override."

---

MODULE.bazel
go.mod
go.sum

This allows Renovate to update them automatically.

Put Go dependencies in go.mod.

---

MODULE.bazel
MODULE.bazel.lock
examples/ext/MODULE.bazel.lock
private/BUILD
private/extensions.bzl
private/repositories.bzl

This partially reverts commit dd78f7fc19b6a470d8365ab96c4e3e4b8ac9ac52.

Simplify non-module development dependencies using use_repo_rule.

---

.github/workflows/bazel-test.yaml
Makefile
build.py

There’s little point running these static checks on all OSes.

Run OS-independent checks only interactively and on GNU/Linux.

---

.github/workflows/bazel-test.yaml
Makefile
build.py

We don’t need to run them on Windows.
This partially reverts commit d71c43ce44c75bc1bcccc024cd4fca56655f42e0.
We have to rename the “license” target to “addlicense” to mark it as phony, as a “license” target clashes with the LICENSE file on macOS and Windows.

Move back some static checks into the Makefile.

---

.bazelrc
REPO.bazel
examples/ext/REPO.bazel
private/BUILD
private/defs.bzl

We want to enable treat_warnings_as_errors only if we're building the main repository (to isolate users from warnings), and only for the targets in our repository.  Specifying a private flag in .bazelrc seems to be the simplest way to achieve this.
This partially reverts commit 0ae8e08e15cd61ef6de98f0797b6e51e666ac371.

Use flag to selectively enable treat_warnings_as_errors.

---

private/emacs.BUILD.template

Probably we don’t want this feature there, as it forces fatal warnings on all users of the generated repository, independent of the compiler they use.

Remove treat_warnings_as_errors feature from Emacs BUILD template.

---

private/defs.bzl

These should be covered by the treat_warnings_as_errors feature.

Remove explicit fatal warning options.

---

elisp/binary.cc
elisp/binary.h
elisp/emacs.cc
elisp/launcher.cc
elisp/process.cc
elisp/process.h
elisp/proto/module.c
elisp/test.cc

They should no longer be necessary now that we use the external_include_paths feature.

Remove warning pragmas.

---

elisp/emacs.h

This was apparently forgotten in commit f2d16b00288615ea97f66f905042a7f397e23953.

Remove warning pragmas from elisp/emacs.h.

---

elisp/process.cc

This allows us to omit the warning pragmas.

Use loop to convert ASCII string.

---

docs/BUILD
elisp/BUILD
emacs/BUILD

It turns out that adding the Starlark library for the file being documented is enough.

Remove duplication of Starlark library targets for Stardoc.

---

docs/BUILD
private/defs.bzl

We only need the protocol buffer message, so the stardoc macro expands to a single rule anyway.

Expand stardoc macros.

---

BUILD
dev/BUILD
docs/BUILD
elisp/BUILD
elisp/proto/BUILD
emacs/BUILD
examples/BUILD
tests/BUILD

According to the documentation they are “Defunct, unused, does nothing”:
https://rules-python.readthedocs.io/en/1.1.0/api/rules_python/python/private/py_library_rule.html#py_library.srcs_version https://rules-python.readthedocs.io/en/1.1.0/api/rules_python/python/private/py_binary_rule.html#py_binary.srcs_version https://rules-python.readthedocs.io/en/1.1.0/api/rules_python/python/private/py_test_rule.html#py_test.srcs_version

Remove srcs_version attributes from Python rules.

---

BUILD
docs/BUILD
elisp/BUILD
elisp/proto/BUILD
emacs/BUILD
examples/BUILD
tests/BUILD

According to the documentation, “For backwards compatibility, the values PY2 and PY3 are accepted, but treated as an empty/unspecified value.”
https://rules-python.readthedocs.io/en/1.1.0/api/rules_python/python/private/py_binary_rule.html#py_binary.python_version https://rules-python.readthedocs.io/en/1.1.0/api/rules_python/python/private/py_test_rule.html#py_test.python_version

Remove unused python_version attributes from Python rules.

---

MODULE.bazel.lock
docs/BUILD
docs/manual.org
elisp/BUILD
elisp/extensions/BUILD
elisp/extensions/elisp.bzl
examples/ext/MODULE.bazel
examples/ext/MODULE.bazel.lock

See
https://docs.google.com/document/d/1L1JFgjpZ7SrBinb24DC_5nTIELeYDacikcme-YcA7xs/view?tab=t.0#heading=h.cy0m49ne5key for the structure that’s nowadays recommended.

Move public definitions out of elisp/extensions.bzl.

---

docs/generate.py
index.html

These are loaded with use_extension instead of load.

Don’t emit load statements for module extensions.

---

gazelle/extension.go
gazelle/language.go
gazelle/resolve.go

This reverts commit e8ff6afe0354fb96f5f696e32e2b7742c3047df3.
The gazelle:resolve directive already provides the same functionality.

Revert "Add a Gazelle directive for a manual import."

---

tests/BUILD

This reverts commit de8baae35e6365e0073e4cc15f34408022ea4aab.
This doesn't appear to be necessary any more.

Revert "Run Go test in the expected directory."

---

.github/workflows/bazel-test.yaml

See https://github.com/bazelbuild/bazel/releases/tag/7.5.0.

Run tests under newly-released Bazel 7.5.0.

---

.github/workflows/bazel-test.yaml
Makefile
build.py

We only ever use the “check” goal now.

Remove target/goal abstraction from build script.

---

elisp/proto/proto-test.el

Emacs 30 will warn about this.

Ignore unused value.

---

tests/ert_test.go
tests/test.el

See https://bugs.gnu.org/76447.

Skip a test that doesn’t work in Emacs 30.1.

---

.github/workflows/bazel-test.yaml

This reverts commit 78c6626eb33a25e25a35337d2a6f3aad9913eb6d.
The profiles are no longer generated (commit d9b397678c2dabc524c0af34073b017de821824c), so the upload will never work.

Revert "Save JSON profile files from CI"

---

elisp/private/tools/ert-runner.el

Commit aeb25f9d3d12a18ef3881e23b32a34615355d4d0 is in all supported Emacs releases.

Remove obsolete workaround.

---

.github/actions/set-up/action.yaml

Python shouldn’t be needed any more after
commit d8e6622566ab76c4d7c20af67e31fa0ad38375a5,
and the Bazel toolchain downloads the correct interpreter automatically.

Don’t install Python as part of the setup action.

---

elisp/private/tools/load_test.py

See https://github.com/bazelbuild/bazel/issues/374#issuecomment-2594713891.

Write runfiles manifest using \n as line separator.

---

MODULE.bazel
elisp/private/emacs_repository.bzl

Emacs releases are rare enough to warrant the duplication.

Hard-code Emacs release archive URLs in MODULE.bazel.

---

.pre-commit-config.yaml
elisp/private/tools/module.def

lld-link doesn’t support them and emits an error
lld-link: error: unknown directive: ﻿
where the “unknown directive” is the byte-order mark.
Without byte-order mark, the Visual C++ linker will interpret the module definition file in the legacy “ANSI” codepage.  Force the file to ASCII-only to ensure this doesn’t cause any trouble.

Don’t add byte-order mark to module definition files.

---

elisp/private/cc_config.bzl

See https://devblogs.microsoft.com/oldnewthing/20170907-00/?p=96956.

Prevent warning when compiling with Clang-CL.

---

.github/actions/set-up/action.yaml
.github/workflows/bazel-test.yaml

On macOS, plain “gcc” invokes Clang, but “gcc-14” invokes GCC.

Specify version suffix for GCC.

---

elisp/private/BUILD

At least for Emacs 30.1, building Emacs with GCC requires the GNU extensions due to its use of the “asm” keyword in src/lisp.h; see https://gcc.gnu.org/onlinedocs/gcc/Extended-Asm.html and https://gcc.gnu.org/onlinedocs/gcc/Alternate-Keywords.html.

Enable GNU extensions when building Emacs with GCC.

---

.bazelrc
MODULE.bazel
MODULE.bazel.lock
examples/ext/MODULE.bazel.lock

See https://github.com/protocolbuffers/protobuf/releases/tag/v30.0.

Update Protocol Buffers to version 30.

---

check.ps1

This finds some errors in the module graph that bazel build doesn’t find.

Also run bazel mod graph.

---

dev/BUILD
dev/version_test.go

This reverts commit 726890338669f8193eab7fae314af5dc75002d39.
The test doesn't pull its weight.

Revert "Add a test that we don’t accidentally try to override production dependencies"

---

elisp/private/tools/compile.el

Otherwise it might start with ~, causing filename relativization to fail.

Expand default directory before quoting it.

---

MODULE.bazel

This reverts commit 9d5621e0a44b2dd6f9a1fbc4524fbb8c18d66142.
New rules_go should have an up-to-date version of Go by default.

Revert "Synchronize Go version with version specified in go.mod"

---

c-std.bazelrc

This reverts commit f436aa170238723ec68e6285ba1ebfa9a43da1e0.
Upstream issue should be fixed by now.

Revert "Work around https://github.com/actions/runner-images/issues/12435"

---

elisp/private/tools/run-test.el
tests/coverage.dat

Otherwise, the record contains bogus uncovered lines.

Initialize fake hit count for first line to function call count.

---

.bazelrc

This reverts commit 312bfa0a5a0212a55b0f07389c9f3d9b7c34e862.
Partial revert: only remove the Visual C++ workaround, which is no longer needed with Protocol Buffer 32, cf. https://protobuf.dev/news/2025-07-16/.

Revert "Update Protocol Buffers to version 30."

---

c-std.bazelrc

This effectively revers commit 18cd259c165aaad20692b0500a58481d64a8bebb. Not using exceptions is a style decision, no need to change the ABI for that.

Remove -fno-exceptions

---

c-std.bazelrc

C++17 is now the default in rules_cc,
cf. https://github.com/bazelbuild/rules_cc/blob/0.2.2/cc/private/toolchain/unix_cc_configure.bzl#L472 and
https://github.com/bazelbuild/rules_cc/blob/0.2.2/cc/private/toolchain/windows_cc_toolchain_config.bzl#L739.

Remove C++ standard selection

---

dev/check_python.py

This reverts commit 37476f16e1bf5e4d7791c7a7bb9a7e5ede635744.

Revert "Generate empty __init__.py files to mimic Bazel behavior"

---

elisp/elisp_library.bzl
elisp/private/tools/BUILD
elisp/runfiles/BUILD
index.html
tests/runfiles/BUILD

It has always been a wart, and we can use select_file from Skylib instead.

Deprecate outs attribute of elisp_library

---

tests/wrap/BUILD

Apparently it’s no longer needed.

Remove executable_only hack from tests/wrap package

---

MODULE.bazel
check.ps1
elisp/BUILD
emacs/BUILD
gazelle/BUILD

Now that we only support the latest minor version for each major version, we don’t need to include the minor version in the names any longer.

Drop minor version numbers from repository and target names

---

elisp/elisp_library.bzl
elisp/private/binary.bzl
elisp/private/compile.bzl
elisp/proto/elisp_proto_library.bzl

This removes the unnecessary intermediate struct.

Have compile function return providers directly
