check_python.py
This should improve filenames in error messages so that they point back into the
source tree rather than the temporary workspace.
=> Run Pytype and Pylint in the workspace directory.

.github/workflows/bazel-test.yaml
See https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows#matching-a-cache-key.
=> Fix incorrect use of cache keys.

BUILD, WORKSPACE, nogo.json
See https://github.com/bazelbuild/rules_go/blob/v0.29.0/go/nogo.rst#setup.
=> Run static analysis on Go files.

docs/emacs.md, emacs/defs.bzl
I added that attribute by mistake in
commit 99011f8fd4f41ec414316cbc729e2f892b49a9a3.
=> Remove unused attribute “cc_toolchain”.

elisp/ert/runner.el
See https://docs.bazel.build/versions/5.0.0/command-line-reference.html#flag--test_runner_fail_fast.
=> Add support for the --test_runner_fail_fast option.

docs/org.py
These don’t have to be subsections, they can just be list elements.
=> Use a compact presentation for parameters, attributes, and fields.

elisp/run_binary.py, elisp/run_emacs.py, elisp/run_test.py
This addresses https://github.com/bazelbuild/bazel/issues/14343.
=> Use executable as argv[0].

.bazelrc
This works around https://github.com/bazelbuild/bazel/issues/15027.
=> Improve heap size on Visual C++.

elisp/runfiles/runfiles.el
Users are never expected to supply custom runfiles implementations, so these
shouldn’t be EIEIO classes.  The public interface shouldn’t change.
=> Switch runfiles implementation to CL structures.

emacs/defs.bzl
Part of bazelbuild/bazel#14727
=> Use a helper to to define the cpp toolchain type

docs/BUILD, elisp/repositories.bzl
See https://github.com/protocolbuffers/protobuf/releases/tag/v21.3.
=> Update to Protocol Buffers 21.3.

WORKSPACE, linux-requirements.txt, macos-requirements.txt, windows-requirements.txt
See https://github.com/bazelbuild/rules_python/releases/tag/0.12.0.
=> Update to rules_python 0.12.0.

elisp/repositories.bzl
See https://github.com/abseil/abseil-cpp/releases/tag/20220623.1.
=> Update to newest Abseil release.

build.py, elisp/BUILD, elisp/repositories.bzl, emacs/BUILD, emacs/emacs_test.py
See https://www.gnu.org/software/emacs/#Releases.
=> Support Emacs 28.2.

WORKSPACE
See https://github.com/bazelbuild/rules_python/releases/tag/0.13.0.
=> Update to rules_python 0.13.0.

WORKSPACE
See https://github.com/bazelbuild/stardoc/releases/tag/0.5.3.
=> Update Stardoc dependency.

elisp/repositories.bzl
See https://github.com/abseil/abseil-cpp/releases/tag/20230125.1.
=> Update Abseil to version 20230125.1.

elisp/run_emacs.py
On Emacs 29, the name of the dump file has a hash suffix, with pushes it over the MAX_PATH limit.
=> Work around filename length limit on Windows.

elisp/repositories.bzl
See https://github.com/bazelbuild/rules_license/releases/tag/0.0.7.
=> Update to rules_license 0.0.7.

elisp/runfiles/BUILD, elisp/runfiles/runfiles-test.el, elisp/runfiles/runfiles.el, elisp/runfiles/test-mapping
See
https://github.com/bazelbuild/proposals/blob/main/designs/2022-07-21-locating-runfiles-with-bzlmod.md.
=> Implement basic support for repository mappings.

.bazelrc, examples/ext/.bazelrc
See https://en.wikipedia.org/wiki/File_URI_scheme#Windows_2.
=> Attempt to construct correct file URLs on Windows.

MODULE.bazel, WORKSPACE
See https://github.com/bazelbuild/bazel-gazelle/releases/tag/v0.34.0.
=> Update Gazelle to version 0.34.0.

MODULE.bazel, elisp/repositories.bzl
See https://github.com/abseil/abseil-cpp/releases/tag/20230802.0.
=> Update to Abseil 20230802.0.

MODULE.bazel, elisp/repositories.bzl
See https://github.com/bazelbuild/rules_python/releases/tag/0.27.0.
=> Update to rules_python 0.27.0.

.github/workflows/bazel-test.yaml, .pylintrc, build.py
This is to work around https://github.com/protocolbuffers/protobuf/issues/12947.
=> Attempt to shorten filenames on Windows.

MODULE.bazel, MODULE.bazel.lock, WORKSPACE, elisp/repositories.bzl, examples/ext/MODULE.bazel.lock, private/repositories.bzl
They incorrectly referenced the main repository instead of the current one.
=> Fix a few incorrect labels.

MODULE.bazel.lock, elisp/defs.bzl, elisp/extensions.bzl, elisp/repositories.bzl, emacs/defs.bzl, examples/ext/MODULE.bazel.lock, examples/ext/repositories.bzl, private/defs.bzl, private/extensions.bzl, private/repositories.bzl, tests/private/defs.bzl
See https://bazel.build/concepts/visibility#load-visibility.
=> Add load visibility to Starlark files.

elisp/proto/BUILD, emacs/BUILD, emacs/defs.bzl, examples/BUILD
See https://github.com/bazelbuild/bazel/issues/2954 and https://github.com/bazelbuild/bazel/pull/14736.
=> Don’t link pure C code with libstdc++.

MODULE.bazel, MODULE.bazel.lock, elisp/repositories.bzl, examples/ext/MODULE.bazel.lock
See https://github.com/abseil/abseil-cpp/releases/tag/20230802.1.
=> Update to Abseil LTS 20230802.1.

elisp/BUILD, elisp/binary_test.cc, elisp/process.cc, elisp/process.h
The binary is effectively the public interface and not its library.
=> Test binary builds using binary target itself.

docs/BUILD, private/defs.bzl
See https://github.com/bazel-contrib/bazel_features/pull/34#issuecomment-1897141981.
=> Check for starlark_doc_extract instead of Bazel version.

.github/workflows/update-lockfiles.yaml, build.py, update_lockfiles
This should be a bit more portable and less hacky.
=> Use GitHub workflow to update MODULE.bazel.lock files.

MODULE.bazel, MODULE.bazel.lock, WORKSPACE, examples/ext/MODULE.bazel.lock
See https://github.com/bazelbuild/rules_python/pull/713 and https://github.com/bazelbuild/rules_python/pull/907.
=> Attempt to work around nondeterminism on Windows.

.github/actions/set-up/action.yaml, .github/workflows/bazel-test.yaml, .github/workflows/update-lockfiles.yaml
See
https://docs.github.com/en/actions/creating-actions/creating-a-composite-action and
https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions.
=> Factor out setup code into a composite action.

MODULE.bazel.lock, build.py, elisp/BUILD, emacs/BUILD, examples/ext/MODULE.bazel.lock, private/repositories.bzl
See https://lists.gnu.org/archive/html/info-gnu-emacs/2024-01/msg00000.html.
=> Add support for Emacs 29.2.

.github/actions/set-up/action.yaml, .github/workflows/bazel-test.yaml, .github/workflows/debug-cache.yaml, .github/workflows/update-lockfiles.yaml, build.py
This means we have to pass them around in the build script.
=> Have GitHub setup action write cache directories into .bazelrc.

MODULE.bazel, MODULE.bazel.lock, elisp/repositories.bzl, examples/ext/MODULE.bazel.lock
See https://github.com/bazel-contrib/bazel_features/releases/tag/v1.4.1.
=> Update to rules_features 1.4.1.

.github/workflows/bazel-test.yaml, .github/workflows/debug-cache.yaml
See https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules?view=powershell-7.4#single-quoted-strings.
=> Prefer single quotes in PowerShell snippets.

MODULE.bazel, MODULE.bazel.lock, WORKSPACE, examples/ext/MODULE.bazel.lock
See https://github.com/bazelbuild/rules_go/releases/tag/v0.45.1.
=> Update to rules_go 0.45.1.

.gitignore, update_lockfiles
=> Split up lockfile update in three phases.

dev/gopackagesdriver
See https://github.com/bazelbuild/rules_go/wiki/Editor-setup#2-launcher-script.
=> Add GOPACKAGESDRIVER launcher script.

elisp/run_binary.py, elisp/run_emacs.py, elisp/run_test.py
This reverts commit 3af60bab84bbfa5909f23a0b2298b0ae5c9e40ce.
This might no longer be needed.
=> Revert "Don’t change the working directory on Windows"

elisp/process.cc
This is useful for cases where we’d throw away any Status value anyway.
=> Add variant of CastNumber that returns std::optional.

elisp/run_binary.py, elisp/run_emacs.py, elisp/run_test.py
The only usage was removed in commit e61268f6451f9575a172b459310e5286e9256561.
=> Remove unused --env options.

MODULE.bazel.lock, dev/linux-requirements.txt, dev/macos-requirements.txt, dev/requirements.in, dev/windows-requirements.txt
See https://github.com/pylint-dev/pylint/releases/tag/v3.1.0.
=> Update to Pylint 3.1.0.

elisp/binary.cc, elisp/binary.h, elisp/emacs.cc, elisp/emacs.h, elisp/launcher.cc, elisp/test.cc, elisp/test.h, private/defs.bzl
This reduces duplication a bit.
=> Move shared code into launcher main function.

.github/actions/set-up/action.yaml
See https://blog.bazel.build/2023/10/06/bwob-in-bazel-7.html#decide-download-modes.
=> Use --remote_download_minimal on GitHub.

elisp/binary.cc, elisp/emacs.cc, elisp/launcher.cc, elisp/main.h, elisp/test.cc, private/defs.bzl
This simplifies the interface for the implementation functions somewhat.
=> Create an argument array in the launcher main function.

MODULE.bazel, MODULE.bazel.lock, elisp/repositories.bzl, examples/ext/MODULE.bazel.lock
See https://github.com/bazel-contrib/bazel_features/releases/tag/v1.7.0.
=> Update to rules_features 1.7.0.

MODULE.bazel, MODULE.bazel.lock, elisp/repositories.bzl, examples/ext/MODULE.bazel.lock
See https://github.com/bazel-contrib/bazel_features/releases/tag/v1.7.1.
=> Update to rules_features 1.7.1.

elisp/run_emacs.py, emacs/build.py
This means that run_emacs.py has less work finding them.
=> Move Emacs installation locations into canonical places.

elisp/run_emacs.py
This reverts commit 852a1555f920c96da5728d6bbde5d67abe23c8bf.
After commit c051a4b426f5f91f5f9163c88e6d5f52ee2eab3f this should no longer be necessary.
=> Revert "Work around filename length limit on Windows."

REPO.bazel, emacs/BUILD, examples/ext/BUILD, examples/ext/REPO.bazel, private/defs.bzl
See https://maskray.me/blog/2022-09-25-layering-check-with-clang#bazel.
=> Enable layering check.

.github/workflows/bazel-test.yaml, MODULE.bazel.lock
See https://github.com/bazelbuild/bazel/releases/tag/7.1.1.
=> Use newest point release of Bazel.

MODULE.bazel, MODULE.bazel.lock, WORKSPACE, build.py, dev/version_test.go, examples/ext/MODULE.bazel.lock
This should make the Buildifier check a bit faster.
See https://github.com/keith/buildifier-prebuilt/releases/tag/6.4.0.
=> Switch to pre-built Buildifier.

.github/actions/set-up/action.yaml
See https://bazel.build/versions/6.0.0/reference/command-line-reference#flag--experimental_repository_cache_hardlinks.
=> Try to save some disk space on GitHub.

private/defs.bzl
This adds a bit of duplication, but makes the logic more obvious.
=> Enable/disable treat_warnings_as_errors explicitly.

MODULE.bazel, MODULE.bazel.lock, elisp/repositories.bzl, examples/ext/MODULE.bazel.lock
See https://github.com/bazelbuild/bazel-skylib/releases/tag/1.6.1.
=> Update to Skylib 1.6.1.

.github/workflows/bazel-test.yaml, MODULE.bazel.lock, examples/ext/MODULE.bazel.lock
See https://github.com/bazelbuild/bazel/releases/tag/7.1.2.
=> Run tests under Bazel 7.1.2.

MODULE.bazel.lock, dev/linux-requirements.txt, dev/macos-requirements.txt, dev/requirements.in, dev/windows-requirements.txt
See https://github.com/pylint-dev/pylint/releases/tag/v3.2.0.
=> Update to Pylint 3.2.0.

MODULE.bazel, MODULE.bazel.lock, elisp/repositories.bzl, examples/ext/MODULE.bazel.lock
See https://github.com/bazelbuild/platforms/releases/tag/0.0.10.
=> Update to Platforms 0.0.10.

MODULE.bazel, MODULE.bazel.lock, elisp/repositories.bzl, examples/ext/MODULE.bazel.lock
See https://github.com/bazel-contrib/bazel_features/releases/tag/v1.11.0.
=> Update to bazel_features 1.11.0.

MODULE.bazel.lock, dev/linux-requirements.txt, dev/macos-requirements.txt, dev/requirements.in, dev/windows-requirements.txt
See https://pypi.org/project/pylint/3.2.2/.
=> Update to Pylint 3.2.2.

MODULE.bazel, MODULE.bazel.lock, WORKSPACE, examples/ext/MODULE.bazel.lock
See https://github.com/bazelbuild/bazel-gazelle/releases/tag/v0.37.0.
=> Update to Gazelle 0.37.0.

MODULE.bazel, MODULE.bazel.lock, elisp/repositories.bzl, examples/ext/MODULE.bazel.lock
See https://github.com/abseil/abseil-cpp/releases/tag/20240116.2.
=> Update to Abseil-C++ 20240116.2.

MODULE.bazel, MODULE.bazel.lock, elisp/repositories.bzl, examples/ext/MODULE.bazel.lock
See https://github.com/protocolbuffers/protobuf/releases/tag/v27.0.
=> Update to Protocol Buffers 27.0.

.github/workflows/bazel-test.yaml, MODULE.bazel.lock, examples/ext/MODULE.bazel.lock
See https://github.com/bazelbuild/bazel/releases/tag/7.2.0.
=> Run tests under Bazel 7.2.0.

.bazelrc
See https://bazel.build/docs/bazel-and-cpp#toolchain-features.
=> Enable --process_headers_in_dependencies.

MODULE.bazel, MODULE.bazel.lock, elisp/repositories.bzl, examples/ext/MODULE.bazel.lock
See https://github.com/bazelbuild/rules_python/releases/tag/0.33.1.
=> Update to rules_python 0.33.1.

MODULE.bazel, MODULE.bazel.lock, elisp/repositories.bzl, examples/ext/MODULE.bazel.lock
See https://github.com/bazel-contrib/bazel_features/releases/tag/v1.13.0.
=> Update to bazel_features 1.13.0.

MODULE.bazel, MODULE.bazel.lock, elisp/repositories.bzl, examples/ext/MODULE.bazel.lock
See https://github.com/protocolbuffers/protobuf/releases/tag/v27.1.
=> Update to Protocol Buffers 27.1.

.github/workflows/bazel-test.yaml, MODULE.bazel.lock, examples/ext/MODULE.bazel.lock
See https://github.com/bazelbuild/bazel/releases/tag/7.2.1.
=> Run tests under Bazel 7.2.1.

MODULE.bazel, MODULE.bazel.lock, elisp/repositories.bzl, examples/ext/MODULE.bazel.lock
See https://github.com/protocolbuffers/protobuf/releases/tag/v27.2.
=> Update to Protocol Buffers v27.2.

dev/linux-requirements.txt, dev/macos-requirements.txt, dev/requirements.in, dev/windows-requirements.txt
See https://pypi.org/project/pylint/3.2.5/.
=> Update to Pylint 3.2.5.

MODULE.bazel, MODULE.bazel.lock, elisp/repositories.bzl, examples/ext/MODULE.bazel.lock
See https://github.com/bazelbuild/rules_python/releases/tag/0.34.0.
=> Update to rules_python 0.34.0.

.github/workflows/bazel-test.yaml, MODULE.bazel.lock, examples/ext/MODULE.bazel.lock
See https://github.com/bazelbuild/bazel/releases/tag/7.3.1.
=> Run tests with Bazel 7.3.1.

dev/linux-requirements.txt, dev/macos-requirements.txt, dev/requirements.in, dev/windows-requirements.txt
See https://pypi.org/project/pylint/3.2.6/.
=> Update to Pylint 3.2.6.

MODULE.bazel, MODULE.bazel.lock, elisp/repositories.bzl, examples/ext/MODULE.bazel.lock
See https://github.com/protocolbuffers/protobuf/releases/tag/v28.1.
=> Update to Protocol Buffers 28.1.

elisp/BUILD, elisp/defs.bzl, elisp/export-org.el, examples/BUILD, examples/config.org, private/defs.bzl
=> elisp_manual: Support additional input files.

dev/linux-requirements.txt, dev/macos-requirements.txt, dev/requirements.in, dev/windows-requirements.txt
See https://github.com/pylint-dev/pylint/releases/tag/v3.3.1.
=> Update to Pylint v3.3.1.

MODULE.bazel, MODULE.bazel.lock, elisp/repositories.bzl, examples/ext/MODULE.bazel.lock
See https://github.com/bazelbuild/rules_python/releases/tag/0.36.0.
=> Update to rules_python 0.36.0.

MODULE.bazel, MODULE.bazel.lock, elisp/repositories.bzl, examples/ext/MODULE.bazel.lock
See https://github.com/protocolbuffers/protobuf/releases/tag/v28.2.
=> Update to Protocol Buffers 28.2.

MODULE.bazel, MODULE.bazel.lock, elisp/repositories.bzl, examples/ext/MODULE.bazel.lock
See https://github.com/protocolbuffers/protobuf/releases/tag/v28.3.
=> Update to Protocol Buffers 28.3.

MODULE.bazel, MODULE.bazel.lock, elisp/repositories.bzl, examples/ext/MODULE.bazel.lock
See https://github.com/bazel-contrib/bazel_features/releases/tag/v1.20.0.
=> Update to bazel_features 1.20.0.

MODULE.bazel, MODULE.bazel.lock, elisp/repositories.bzl, examples/ext/MODULE.bazel.lock
See https://github.com/bazelbuild/bazel-skylib/releases/tag/1.7.1.
=> Update to Skylib 1.7.1.

MODULE.bazel, MODULE.bazel.lock, elisp/repositories.bzl, examples/ext/MODULE.bazel.lock
See https://github.com/protocolbuffers/protobuf/releases/tag/v29.1.
=> Update to Protocol Buffers v29.1.

MODULE.bazel, MODULE.bazel.lock, examples/ext/MODULE.bazel.lock
See https://github.com/abseil/abseil-cpp/releases/tag/20240722.0.
=> Upgrade Abseil-C++ to 20240722.0.

.github/actions/set-up/action.yaml
See https://github.com/msys2/setup-msys2?tab=readme-ov-file#msys2-location.
=> Don’t hard-code MSYS2 location.

.github/actions/set-up/action.yaml, MODULE.bazel, MODULE.bazel.lock, docs/BUILD, examples/ext/MODULE.bazel.lock, private/extensions.bzl, private/texinfo.BUILD.template
This is cleaner than having genrule search for it.
=> Generate repository for the Makeinfo program.

gazelle/builtin.go, gazelle/feature.go, gazelle/generate.go, gazelle/generate_test.go, gazelle/imports.go, gazelle/loadpath.go, gazelle/resolve.go, gazelle/resolve_test.go
These should never have been exported in the first place.
=> Unexport Imports and Feature.

elisp/private/tools/build_emacs.py
See https://docs.python.org/3/library/codecs.html#error-handlers.
=> Fix incorrect error handler name.

MODULE.bazel, check.ps1, elisp/BUILD, emacs/BUILD
See https://lists.gnu.org/archive/html/info-gnu-emacs/2025-02/msg00009.html.
=> Import Emacs 30.1.

tests/runfiles/BUILD, tests/runfiles/runfiles-test.el, tests/runfiles/testäα𝐴🐈'.txt
This reverts commit f2ac10389ae257f96816695ebeb7fe1463ff4980.
Try this again.
=> Revert "Revert "Extend tests to cover non-ASCII and special characters""

.bazelrc, .github/actions/set-up/action.yaml, .github/workflows/bazel-test.yaml, elisp/private/BUILD, elisp/private/cc_config.bzl, elisp/private/cc_launcher_config.bzl, elisp/proto/BUILD, examples/ext/.bazelrc, examples/ext/MODULE.bazel
See https://bazel.build/configure/windows#clang.
=> Support building with Clang on Windows.

.github/workflows/bazel-test.yaml, MODULE.bazel.lock, examples/ext/MODULE.bazel.lock
See https://github.com/bazelbuild/bazel/releases/tag/8.3.0 and https://github.com/bazelbuild/bazel/releases/tag/8.3.1.
=> Run tests under Bazel 8.3.1.

dev/check_python.py, elisp/private/tools/build_emacs.py, elisp/private/tools/run_test.py, elisp/private/tools/wrap.py
Pytype accepts this, but Mypy doesn’t.
=> Don’t reassign values with different types to variables

docs/generate.py, examples/bin_test.py, tests/emacs_test.py, tests/empty_test.py, tests/proto/module_test.py, tests/tools/binary_test.py, tests/tools/load_test.py, tests/tools/manifest_test.py
See https://github.com/theoremlp/rules_mypy/issues/112.
=> Suppress false Mypy positives for external repository imports

.bazelrc, MODULE.bazel, MODULE.bazel.lock, Makefile, dev/BUILD, dev/mypy.bzl, update_lockfiles
With the sunsetting of Pytype (https://github.com/google/pytype/issues/1925), we should switch to another type checker.
See https://github.com/theoremlp/rules_mypy/blob/main/readme.md.
=> Run Mypy aspect

elisp/private/cc_config.bzl, elisp/proto/module.c
See https://learn.microsoft.com/en-us/cpp/build/reference/zc-stdc?view=msvc-170.
=> Unconditionally require __STDC__

elisp/runfiles/runfiles.el, tests/runfiles/runfiles-test.el, tests/runfiles/test-mapping
See https://github.com/bazelbuild/bazel/issues/26262.
=> Add support for compact repo mappings

dev/check_python.py
This reverts commit 482e18761fa6f0b5a1aaf214765d1bc84dfbbf03.
This workaround doesn't seem to be necessary any more.
=> Revert "Work around another issue with import paths"

dev/check_python.bzl, dev/check_python.py
This effectively reverts commit e97eb248b17cc319c129be5ec4601129b78328bb.
=> Remove unused --workspace-name flag

elisp/proto/elisp_proto_library.bzl
They should be the compiled generated files (without the deprecated bundle file) to mimic the behavior of elisp_library.
=> elisp_proto_library: fix default outputs

dev/run_pylint.py
See https://pylint.readthedocs.io/en/stable/user_guide/usage/output.html#output-options.
=> Have Pylint create the dummy output file

tests/emacs_test.go
See https://www.gnu.org/prep/standards/html_node/_002d_002dversion.html.
=> Check output of emacs --version
